export const Produk = [
  {
    id_produk: "produk-0001",
    tipe_produk: "Fisik",
    nama_produk: "Botol Minum Daur Ulang",
    gambar_produk: "/public/assets/lampu.jpg",
    desc_produk: "Terbuat dari plastik PET bekas yang telah diproses ulang.",
    stok: "50",
    harga_produk: "600",
  },
  {
    id_produk: "produk-0002",
    tipe_produk: "Fisik",
    nama_produk: "Tas Belanja Kain Daur Ulang",
    gambar_produk: "/public/assets/lampu.jpg",
    desc_produk: "Dibuat dari limbah tekstil industri yang dijahit ulang.",
    stok: "40",
    harga_produk: "550",
  },
  {
    id_produk: "produk-0003",
    tipe_produk: "Fisik",
    nama_produk: "Tempat Pensil Karton",
    gambar_produk: "/public/assets/lampu.jpg",
    desc_produk: "Karton bekas yang diproses menjadi tempat pensil unik.",
    stok: "30",
    harga_produk: "350",
  },
  {
    id_produk: "produk-0004",
    tipe_produk: "Fisik",
    nama_produk: "Notebook Kertas Daur Ulang",
    gambar_produk: "/public/assets/lampu.jpg",
    desc_produk: "Kertas bekas yang dijilid ulang menjadi buku catatan.",
    stok: "100",
    harga_produk: "450",
  },
  {
    id_produk: "produk-0005",
    tipe_produk: "Fisik",
    nama_produk: "Dompet Vinyl Bekas",
    gambar_produk: "/public/assets/lampu.jpg",
    desc_produk: "Dibuat dari banner iklan bekas yang dijahit menjadi dompet.",
    stok: "25",
    harga_produk: "700",
  },
  {
    id_produk: "produk-0006",
    tipe_produk: "Fisik",
    nama_produk: "Pot Tanaman Plastik Daur Ulang",
    gambar_produk: "/public/assets/lampu.jpg",
    desc_produk: "Plastik rumah tangga bekas yang dilelehkan dan dicetak ulang.",
    stok: "60",
    harga_produk: "400",
  },
  {
    id_produk: "produk-0007",
    tipe_produk: "Fisik",
    nama_produk: "Gantungan Kunci Tutup Botol",
    gambar_produk: "/public/assets/lampu.jpg",
    desc_produk: "Tutup botol bekas yang dikreasikan menjadi gantungan unik.",
    stok: "80",
    harga_produk: "250",
  },
  {
    id_produk: "produk-0008",
    tipe_produk: "Fisik",
    nama_produk: "Lampu Meja Kaleng Bekas",
    gambar_produk: "/public/assets/lampu.jpg",
    desc_produk: "Kaleng bekas yang dimodifikasi menjadi lampu meja kreatif.",
    stok: "20",
    harga_produk: "850",
  }
];
